# -*- coding: utf-8 -*-
"""Baseline opponents for the Gomoku RL assignment.

Two baselines are used by evaluate.py, in fixed configurations that MUST NOT be
modified by students.

    pure_mcts : classical MCTS with uniform-random rollouts (no neural network).
                n_playout = 1000. Strength: weak-to-medium.
    alphazero : pretrained AlphaZero policy/value net (best_policy_6_6_4.model)
                driving MCTS with n_playout = 400. Strength: medium-to-strong.

Both baselines are effectively deterministic (visit-count argmax / temp=1e-3).
The evaluation harness seeds numpy/random before every game so reproducibility
holds even though the internal MCTS rollouts use randomness.

Do not edit this file. evaluate.py imports these symbols directly.
"""
from __future__ import print_function

import os
import pickle


BOARD_SIZE = 8
N_IN_ROW = 5

_HERE = os.path.dirname(os.path.abspath(__file__))
ALPHAZERO_MODEL = os.path.join(_HERE, "best_policy_8_8_5.model")

PURE_MCTS_PLAYOUTS = 1000
ALPHAZERO_PLAYOUTS = 400

BASELINE_NAMES = ("pure_mcts", "alphazero")


def _make_pure_mcts():
    from mcts_pure import MCTSPlayer as PureMCTSPlayer

    return PureMCTSPlayer(c_puct=5, n_playout=PURE_MCTS_PLAYOUTS)


def _make_alphazero():
    from mcts_alphaZero import MCTSPlayer
    from policy_value_net_numpy import PolicyValueNetNumpy

    with open(ALPHAZERO_MODEL, "rb") as f:
        try:
            params = pickle.load(f)
        except UnicodeDecodeError:
            f.seek(0)
            params = pickle.load(f, encoding="bytes")
    policy = PolicyValueNetNumpy(BOARD_SIZE, BOARD_SIZE, params)
    return MCTSPlayer(policy.policy_value_fn, c_puct=5, n_playout=ALPHAZERO_PLAYOUTS)


_FACTORIES = {
    "pure_mcts": _make_pure_mcts,
    "alphazero": _make_alphazero,
}


def make_baseline(name):
    """Return a fresh baseline player. The returned player implements
    set_player_ind(int) and get_action(board)."""
    if name not in _FACTORIES:
        raise ValueError(
            "Unknown baseline '{}'. Options: {}".format(name, list(_FACTORIES))
        )
    return _FACTORIES[name]()
